### PR TITLE
Upgrade odp_theme for CKAN 2.8

### PR DESCRIPTION
**Pull request by KlaasH**
### Overview

Upgrades the overridden templates to work with CKAN 2.8 and override the 2.8 templates.

I tried to get upstream updates and apply our overrides by sometimes copying the new upstream template and applying the changes we had made to the old template and sometimes working from the existing overridden template to apply upstream changes.  I.e. "copy then modify" if the upstream changes were extensive and/or our changes were small, "apply updates manually" if the upstream changes were minor and/or our modifications were extensive (especially in cases where we're only overriding one block).

In a couple places, more blocks were added upstream so I could reduce the amount of unmodified code that we have copied into our templates.

~Large parts of this are working, but some parts are crashing.  Most frustratingly, the home view crashes in a way that, as far as I can tell, doesn't send the error to the logs.  I.e. something inside the `layout1.html` snippet is crashing but the error is getting swallowed.~ See below for update.

### Notes

Thanks to @designmatty for sitting down with me and working out the fixes to make the home page look right.

The most noticeable upstream changes to the styling are that the pages are wider and they use bootstrap column classes (rather than bootstrap-reminiscent classes like "span6").

### To test

- Check out this branch in your `ckanext-odp_theme` directory.
- Check out develop in your `opendataphilly-ckan` directory.
- In the `deployment/ansible/app.yml` file in `opendataphilly-ckan`, uncomment the `- { role: "ckanext-odp_theme" }` line.
- Provision according to the instructions in https://github.com/azavea/opendataphilly-ckan/pull/76, but with the added wrinkle that the database machine currently needs to be provisioned on commit [3a872c0a](https://github.com/azavea/opendataphilly-ckan/commit/3a872c0a4d7a73dc9375fdcb58f1f1e60b043ba9)
- Navigate the site.  It should look like the production site (see https://github.com/azavea/urban-apps/issues/147 for a workaround for the missing images) except for the width change.
- Crashes or layout changes that look bad are bugs.  Layout changes that look fine are upgrades :grin:

Resolves https://github.com/azavea/urban-apps/issues/158

### CODE REVIEW

**Comment by KlaasH** [comment]
It looks like the crash in `layout1.html` was because it was trying to load a snippet from the `related` plugin which is not installed (see https://github.com/azavea/urban-apps/issues/155).  Commenting that out made it stop crashing, and the rest of the page looks OK but not exactly right--it's using more width, which is happening on other pages as well and seems fine to me, but there are other layout bugs like the fact that the carousel buttons are off the bottom of their section (i.e. invisible because they're underneath the next section) and the "Search" section has a bunch of useless height for some reason.

image

**Comment by KlaasH** [comment]
Updated/no longer WIP:
- Rebased the branch and redirected the PR to develop, now that PR #58 is merged
- Added a couple "Notes" to the initial comment
- Modified the testing instructions to note the "provision the DB VM on a specific commit" workaround and elaborate on what expected behavior looks like

**Review by flibbertigibbet — APPROVED** [review]
Looks good! Just found a couple of console errors while navigating. I was also unable to link to an external dataset, but that's probably due to reasons unrelated to the theme upgrade.

Apart from the home page, there's a console error showing on the other pages that seems to be related to a carousel:

odp_console_error

And also on the user edit page, there's a console error:
odp_user_edit_console_error

**Comment by KlaasH** [comment]
I fixed the error from `favorite.js` and also the carousel issue I saw while investigating it (it would show the first image, and the arrows worked to switch away from that one and back, but it wouldn't show any others).

The password field error is unfortunately coming from upstream: https://github.com/ckan/ckan/blob/ckan-2.8.1/ckan/templates/user/edit_user_form.html#L30-L37
We could override the template to work around it, but I'm inclined to say we should make a separate issue for that if we feel it matters enough to address it.

Is "I was also unable to link to an external dataset" the thing you mentioned on Slack whereby the little file type badges on the datasets in the list led to 404 pages, or is that something else?  I fixed those links, but if it's something else I'd like to try to reproduce it to see whether it's caused by these changes or not.

**Comment by KlaasH** [comment]
Upon reflection, I'm going to go ahead and merge this, and we can open issues for any residual problems.

**Pull request merged**
