### PR TITLE
Allow sysadmins to delete unpublished dataset feedback

### PR DESCRIPTION
**Pull request by sharph**
deletecomment

### CODE REVIEW

**Comment by sharph** [comment]
@jfrankl may need to do some restyling now that we've done away with most of the fields we had.

**Comment by jfrankl** [comment]
This looks really different from before. Did we simplify the form so it
only shows one text area instead of the multiple choices?

On Fri, Feb 13, 2015 at 3:43 PM, Sharp Hall notifications@github.com
wrote:

> @jfrankl https://github.com/jfrankl may need to do some restyling now
> that we've done away with most of the fields we had.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/azavea/ckanext-odp_theme/pull/35#issuecomment-74323631
> .

## 

Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
http://twitter.com

**Comment by sharph** [comment]
Yes, based on feedback from City of Philadelphia I believe.

**Comment by sharph** [comment]
deletecomment2

**Comment by jfrankl** [comment]
Looks sharp.

+1

On Fri, Feb 13, 2015 at 4:18 PM, Sharp Hall notifications@github.com
wrote:

> [image: deletecomment2]
> https://cloud.githubusercontent.com/assets/539905/6195421/f385213a-b39b-11e4-8e59-c8f82e732404.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/azavea/ckanext-odp_theme/pull/35#issuecomment-74328520
> .

## 

Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
http://twitter.com

**Comment by jfrankl** [comment]
(Sorry.)

On Fri, Feb 13, 2015 at 4:20 PM, Jeff Frankl jfrankl@azavea.com wrote:

> Looks sharp.
> 
> +1
> 
> On Fri, Feb 13, 2015 at 4:18 PM, Sharp Hall notifications@github.com
> wrote:
> 
> > [image: deletecomment2]
> > https://cloud.githubusercontent.com/assets/539905/6195421/f385213a-b39b-11e4-8e59-c8f82e732404.png
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/azavea/ckanext-odp_theme/pull/35#issuecomment-74328520
> > .
> 
> ## 
> 
> Jeff Frankl, UI/UX Designer
> 
> Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
> Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
> http://twitter.com

## 

Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
http://twitter.com

**Comment by ddohler** [comment]
+1

**Pull request merged**
